version: "3.8"

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
    command: redis-server --requirepass local-redis-pass
    networks:
      - go-programming-network

  postgres:
    image: postgres:14
    restart: always
    profiles:
      - sql_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pwd
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    networks:
      - go-programming-network
  
  # ui for postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    profiles:
      - sql_database
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    depends_on:
      - postgres
    networks:
      - go-programming-network

  mongo:
    image: mongo
    restart: always
    profiles:
      - nosql_database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d/
    networks:
      - go-programming-network

  # ui for mongo
  mongo-express:
    image: mongo-express
    restart: always
    profiles:
      - nosql_database
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_DATABASE: mongo
    depends_on:
      - mongo
    networks:
      - go-programming-network

networks:
  go-programming-network:
    driver: bridge
    name: go-programming-network