version: "3.8"

services:

  postgres:
    image: postgres:14
    profiles:
      - databases
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_pwd
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    profiles:
      - databases
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    depends_on:
      - postgres

  redis:
    profiles:
      - databases
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
    command: redis-server --requirepass local-redis-pass
    ports:
      - "6379:6379"
